### PR TITLE
replace placeholder

### PR DESCRIPTION
**Pull request by holanita**
Asim has a placeholder in his profile under topics. Let's remove or replace with valid text.

### CODE REVIEW

**Comment by holanita** [comment]
@jawache @zanete this is just a reminder to review and update Asim's speaker profile before COP as this might get some visibility due to the event. we should at least remove the placeholder.

**Comment by zanete** [comment]
@holanita  (cc @osamajandali ) this might not result in the desired effect because the backend solution for speakers was changed and as I understand no longer read from this repository the same way. I will add a ticket for @osamajandali to remove it or better yet, update with the correct information if we have it somewhere?

**Comment by holanita** [comment]
@zanete I think this is fine. I've edited the current code not the old one. my PR has no conflicts with the current code.

**Comment by zanete** [comment]
ok, I don't feel confident enough to review and merge as I haven't been involved in this process, I will leave for @jawache

**Comment by jawache** [comment]
Thanks @holanita , approved. Will merge :)

**Pull request merged**
